version: '3'

services:
  container_nginx:
    image: nginx:stable-alpine
    container_name: container_nginx
    ports:
      - "port_host:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - container_php
      - container_mysql
    networks:
      - name_networks

  container_mysql:
    image: mysql:5.7.22
    container_name: container_mysql
    restart: unless-stopped
    tty: true
    volumes:
     - ./DB:/var/lib/mysql
    ports:
      - "port_local_db:3306"
    environment:
      MYSQL_DATABASE: video_player
      MYSQL_USER: video_player
      MYSQL_PASSWORD: ajadam
      MYSQL_ROOT_PASSWORD: ajadam
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - name_networks

  container_php:
    container_name: container_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    tty: true
    environment:
      XDEBUG_CONFIG: "remote_host=198.168.220.1"
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    links:
      - container_mysql
    networks:
      - name_networks

networks:
  name_networks:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 198.168.222.0/28
